### ISSUE TITLE
Unable to implement for CameraX PreviewView

### ISSUE THREAD

**Issue by nurhadidev** [hyuwah/DraggableView#15]
Hi, thanks for the nice library.!!

I was successfully implement this library for the ImageView, but I am unable to implement it for CameraX PreviewView. What I want to achieve is provide a thumbnail video preview that user can move it around the screen.

thanks in advance for any suggestions.

**Comment by hyuwah** [comment]
Hi mas @nurhadidev, thank you for your interest in this library.  🙏 

Regarding your issue in CameraX PreviewView implementation, does this kind of behavior in the following video is what you're expecting?

https://github.com/hyuwah/DraggableView/assets/5181388/d3d49a76-dad3-4427-a384-9a03701db0ca

In the video above, the CameraX's `PreviewView` is turned into draggable view with `XY` sticky mode. If that's what you're looking for, I could give you the code example.

I'm using these version for the camerax libs
```
val camerax = "1.2.3"
implementation("androidx.camera:camera-camera2:${camerax}")
implementation("androidx.camera:camera-lifecycle:${camerax}")
implementation("androidx.camera:camera-view:${camerax}")
```

Here's the code example: [**Test App.zip**](https://github.com/hyuwah/DraggableView/files/12868163/Test.App.zip)

**Comment by nurhadidev** [comment]
Thank you so much for the code, now it works.

Actually, the problem is my poor code. I wrapped PreviewView in a CardView, and make it as draggable view, that is way when I touched on the preview surface, it won't work.

and again, matur nuwun mas, ;)

**Comment by hyuwah** [comment]
Your welcome mas, I'm glad it helped.
I'll mark this as resolved and close the issue, ya.
