### ISSUE TITLE
implementation in scroll view?

### ISSUE THREAD

**Issue by Prakash19921206** [hyuwah/DraggableView#4]
Hi,

If we make a view draggable and its parent layout/root layout being a vertical scroll view.
then we can only move dragabble view horizontally , if we try to move it vertically it scrolls the activity.
I thought of disabling and enable back scroll view using `onTouchListener `(using `MotionEvent.ACTION_DOWN `and `MotionEvent.ACTION_UP`)  but onTouchListener do not work if we make any view as dragabble 

although even if scroll view is disabled, dragabble view still do not move vertically.
i tried disabling the scroll view like below
```
scrollView.setOnTouchListener(new View.OnTouchListener()
{
    @Override
    public boolean onTouch(View v, MotionEvent event)
    {
        return true;
    }
});
```
any work around for this?

Thanks & Regards
Prakash

**Comment by hyuwah** [comment]
Hi @Prakash19921206,

Thank you for your interest in using this library

Regarding the implementation in scroll view, could you share your layout structure or the use case / scenario you want to achieve with the draggable view?

Draggable view can conflict with touch event from scroll view if it is placed inside the scroll view. One way to make it work is to place it on the same level as the scroll view (we need a viewgroup to wrap both view).

```xml
<!-- Parent / Root -->
<FrameLayout>

    <ViewThatWantToBeDraggable/>

    <ScrollView>
        <LinearLayout>
            <!-- Scroll view content -->
        </LinearLayout>
    </ScrollView>

</FrameLayout>
```

This way, the scroll view touch event won't intercept the touch event of draggable view.

I've made a small example regarding this

![draggableview-scrollableview](https://user-images.githubusercontent.com/5181388/78323064-e07e2c00-759a-11ea-8b78-4ed681221d7b.gif)

Is that the kind of behavior you want to achieve?

**Comment by Prakash19921206** [comment]
Thanks for your reply.

I also needed dragable view to only move within some boundary(LinerLayout) - just like a slider header
I tried a different approach, 
1. Implemented Custom Scroll view to enable/disable scroll whenever we want, based on [stackoverflow ](https://stackoverflow.com/a/5763815/4359558) answer
2.  used [this ](https://stackoverflow.com/a/39165696/4359558) class to set draggable view and limit its movement within a defined boundary - i modified this class a little to enable/disable scroll view when dragabble move is moving around [using `ACTION_UP `and `ACTION_DOWN `touch listener]


[Here](https://github.com/hyuwah/DraggableView/files/4425342/DragView_within_boundary.zip) is a sample project with above mentioned code implementation
