### ISSUE TITLE
ClassCastException raise when cast ViewRootImpl cast to View

### ISSUE THREAD

**Issue by sianyi** [hyuwah/DraggableView#5]
Hi Developer 

Thanks for sharing the DraggableView library, it is very convenient.
But I found a bug when I use makeDraggable on an overlay view.

Here is an example that I make an overlay TextView with DraggableView.

```
    private void InitialTextView(){
        floatingLuxView = new TextView(this);
        floatingLuxView.setText("Hi I am a overlay View");
        floatingLuxView.setTextColor(Color.rgb(255, 255, 0));
        floatingLuxView.setTextSize(32f);
        floatingLuxView.setShadowLayer(10, 5, 5, Color.rgb(56, 56, 56));

        DraggableUtils.makeDraggable(floatingLuxView);

        windowManager = (WindowManager)getSystemService(WINDOW_SERVICE);

        int LAYOUT_FLAG;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            LAYOUT_FLAG = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            LAYOUT_FLAG = WindowManager.LayoutParams.TYPE_PHONE;
        }

        params = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                LAYOUT_FLAG,
                        WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN |
                        WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                PixelFormat.TRANSLUCENT);
        params.gravity = Gravity.TOP|Gravity.LEFT;

    }
```
Then the App crash and show ClassCastException:
java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View
at io.github.hyuwah.draggableviewlib.DraggableUtils$makeDraggable$1.onTouch(Extensions.kt:24)

Which point to the below code.
```
    setOnTouchListener { v, event ->
        val viewParent = v.parent as View
        val parentHeight = viewParent.height
```

It mentioned that the parent of the TextView I made is a ViewRootImpl not a View.
I am not pretty sure how to fix it in a good way, may I consult your idea ?

**Comment by hyuwah** [comment]
Hi @sianyi

Thanks for trying out this library

First of all, could you explain what kind of behavior you want to achieve?
1. Is it a simple TextView that floats (and drag-able) inside an Activity / Fragment? Or inside a CustomView? Where does the `InitialTextView()` being called from?
2. Then, does the TextView has to be inflated / created programmatically?

If the answer of first question is inside activity or fragment & the second question is true, as far as i know, we have to add the TextView to ViewGroup inside the activity / fragment layout

So, assuming you have this layout and activity code

```xml
<!-- activity_example.xml -->
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/root_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <!-- Other View or ViewGroup -->
        
</RelativeLayout>

```
We have RelativeLayout root with `root_view` as it's id

```java
// ExampleActivity.java
public class ExampleActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_example);

        InitialTextView();
    }

    private void InitialTextView(){
        TextView floatingLuxView = new TextView(this);
        floatingLuxView.setText("Hi I am a overlay View");
        floatingLuxView.setTextColor(Color.rgb(255, 255, 0));
        floatingLuxView.setTextSize(32f);
        floatingLuxView.setShadowLayer(10, 5, 5, Color.rgb(56, 56, 56));

        DraggableUtils.makeDraggable(floatingLuxView);

        WindowManager windowManager = (WindowManager)getSystemService(WINDOW_SERVICE);

        int LAYOUT_FLAG;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            LAYOUT_FLAG = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            LAYOUT_FLAG = WindowManager.LayoutParams.TYPE_PHONE;
        }

        WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                WindowManager.LayoutParams.WRAP_CONTENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                LAYOUT_FLAG,
                WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN |
                        WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                PixelFormat.TRANSLUCENT);
        params.gravity = Gravity.TOP|Gravity.LEFT;

        // We need to add this floatingLuxView to any ViewGroup on the layout
        // in this case i'm adding it to the root_view
        ViewGroup rootView = findViewById(R.id.root_view);
        rootView.addView(floatingLuxView);
    }
}

```
We have the `InitialTextView()` function inside the activity and is being called from `onCreate()`,
then we just need to add the `floatingLuxView` to the `rootView`

Here's the result
![draggableview-issue-5](https://user-images.githubusercontent.com/5181388/80899397-ca01f680-8d39-11ea-96e6-0620108ffaae.gif)

If that's the behavior you'd expect, it would be easier to just write the `TextView` directly on the xml code, so you don't have to deal with attaching / inflating it to the layout manually.

As for the crash issue, i've tried the code you provide without above modification (adding it to the `rootView` whatsoever), inside a simple activity, but i can't reproduce the crash. 
It runs, the TextView doesn't show up, but it doesn't crash. Could you show me your full code of your implementation?

**Comment by sianyi** [comment]
Hi I make a simple app for your reference

https://github.com/sianyi/example_of_floating_lux

I would like to show a floating text view on top of screen and overlay others application.
In addition, I hope it is Draggable.

In the simple APP you can see the red color TextView is inside the main Activity and it works well but the yellow color textView is overlay on other application and will rise Exception when I touch it.

**Comment by hyuwah** [comment]
Hi @sianyi 

I updated the library to support the case of overlay draggable view over other app via `makeOverlayDraggable()`. Can you please check it out?

I've also updated the readme regarding it's usage example 

Here's the preview on emulator (there's no light sensor on emulator so the value stays 0.0)
![draggableview-issue-5-4](https://user-images.githubusercontent.com/5181388/80954448-97362c00-8e27-11ea-93cb-11699e462835.gif)

On a sidenote, i can't make it work on API 19 (Kitkat) device, the overlay was removed as soon as the activity goes into background. I haven't tried it on a `Service` though.

**Comment by sianyi** [comment]
Thanks!, it is really help.
I will try it.

**Comment by hyuwah** [comment]
It might take a while for the updated version to appear on JitPack (several minutes maybe, but it shouldn't take long)

**Comment by sianyi** [comment]
I have tested the new version and it works well on my devices, thank you very much.
